# Generated by Django 4.1.7 on 2023-04-04 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'admin'), ('student', 'student')], default='student', max_length=10),
        ),
    ]
