# Generated by Django 4.1.7 on 2023-04-11 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_rename_category_id_book_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='authors',
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(default='shakesphere', max_length=250),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
